### ISSUE TITLE
Cannot access: https://learn.co/tracks/javascript-with-style

### ISSUE THREAD

**Issue by dannyenfp** [learn-co-curriculum/js-dom-and-events-intro-to-the-dom-readme#4]
When I put in https://learn.co/tracks/javascript-with-style, I am automatically transferred to: https://learn.co/tracks/full-stack-web-development-v6

Why is this?

**Comment by maxwellbenton** [comment]
Hi @dannyenfp,

Thank you for providing this feedback! 

This lesson was using an out of date link as an example. Since it can't be located, learn.co redirects to the main page of the track you're currently on. We've changed the link so students will now be able to follow along correctly.

Thank you for contributing and helping future students!
